### ISSUE TITLE
Missing IMPROVE_RESULT

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/TGSA#13]
https://github.com/JDACS4C-IMPROVE/TGSA/blob/6465d90575485a362d1c0f0e9ad0071e059005d0/candle_train.py#L169

This is needed for the HPO workflow in this version. Please add where appropriate:

    # Supervisor HPO
    print("\nIMPROVE_RESULT val_loss:\t{}\n".format(scores["val_loss"]))
    with open(Path(args.output_dir) / "scores.json", "w", encoding="utf-8") as f:
        json.dump(scores, f, ensure_ascii=False, indent=4)

**Comment by smujiang** [comment]
fixed.

**Comment by wilke** [comment]
Run the code: Getting error. 

1. Please make sure you print IMPROVE_RESULT only once at the end (not in the for loop)
2. You should be able to print rmse with rmse.item() (that's why can serialize the json)
3. Please test the code and let alex now


```
Validation rmse:0.0979992002248764

IMPROVE_RESULT val_loss:        0.0979992002248764

Traceback (most recent call last):
  File "/usr/local/TGSA/candle_train.py", line 183, in <module>
    main()
  File "/usr/local/TGSA/candle_train.py", line 180, in main
    run(gParams)
  File "/usr/local/TGSA/candle_train.py", line 165, in run
    json.dump([rmse, MAE, r2, r], f, ensure_ascii=False, indent=4)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/conda/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/conda/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable

real    53m57.282s
user    60m57.598s
sys     24m43.984s
```

**Comment by smujiang** [comment]
Thanks for pointing out the issues. I've updated the code. Will let you know my testing result soon.

**Comment by smujiang** [comment]
problem fixed
=====Epoch 1
Training...
Iteration: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3670/3670 [14:54<00:00,  4.10it/s]
Train Loss:0.010837402194738388
Evaluating...
Iteration: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 459/459 [01:39<00:00,  4.62it/s]
Validation rmse:0.10591184347867966
EarlyStopping! Finish training!
Training time: 994.249773979187 s


IMPROVE_RESULT:	0.10591184347867966
