### ISSUE TITLE
No path to candle_glue.sh

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/TGSA#4]
Command: `singularity run --nv --bind `pwd`/tmp:/candle_data_dir build/TGSA.sif train.sh 1 /candle_data_dir --epochs 1`
Status: **Failed**

Output:
```
CMD = python /usr/local/TGSA/candle_train.py --epochs 1
/usr/local/TGSA/train.sh: line 59: ./candle_glue.sh: No such file or directory
using original data placed in /candle_data_dir
/candle_data_dir//Data
/usr/local/TGSA/train.sh: line 77: ./candle_glue.sh: No such file or directory
using original data placed in /candle_data_dir//Data
using CUDA_VISIBLE_DEVICES 1
```

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/Singularity/issues/52#issuecomment-1720064459_

**Comment by smujiang** [comment]
added candle_glue.sh to the root folder
