### ISSUE TITLE
Download ignoring setting for candle_data_dir

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/TGSA#5]
Command: `singularity run --nv --bind `pwd`/tmp:/candle_data_dir build/TGSA.sif train.sh 1 /candle_data_dir --epochs 1`
Status: **Failed**

Output:
```
 'weight_path': ''}
Training on Pilot1 dataset
Traceback (most recent call last):
  File "/usr/local/TGSA/candle_train.py", line 205, in <module>
    main()
  File "/usr/local/TGSA/candle_train.py", line 202, in main
    run(gParams)
  File "/usr/local/TGSA/candle_train.py", line 111, in run
    os.makedirs(output_root_dir)
  File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr/local/TGSA/benchmark_dataset_generator/improve_data_dir'
```

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/Singularity/issues/52#issuecomment-1720064459_

**Comment by wilke** [comment]
This is a blocking issue. Please check as soon as possible.

**Comment by smujiang** [comment]
Updated the code and README, could you please check if the issue is fixed?

**Comment by wilke** [comment]
Updated train.sh, last fix https://github.com/JDACS4C-IMPROVE/TGSA/commit/ab109b841b21cb12f2f64d24f27a287113451d2f
