### ISSUE TITLE
Invalid train.sh script

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/TGSA#7]
Please use this template for the train.sh. Your script is setting not any environment variables. 

https://github.com/JDACS4C-IMPROVE/Singularity/blob/develop/src/templates/train.sh

**Comment by smujiang** [comment]
updated train.sh and readme.md, could you please check again?

**Comment by wilke** [comment]
Updated train.sh, last fix https://github.com/JDACS4C-IMPROVE/TGSA/commit/ab109b841b21cb12f2f64d24f27a287113451d2f
